### ISSUE TITLE
Error after Update! (0.1.10)

### ISSUE THREAD

**Issue by Hadea4711** [NorthernMan54/homebridge-yamaha-home#36] opened 2020-05-18 09:44 UTC
Hi everybody,

after update I've got (0.1.10) this error message: 

<img width="872" alt="Error" src="https://user-images.githubusercontent.com/58209844/82198435-9bb91500-98fc-11ea-825e-6c9761a9cbab.png">

Do you have any ideas to solve this problem?

**Comment by NorthernMan54** [comment] 2020-05-19 03:09
These are just warnings and can be ignored

**Comment by Hadea4711** [comment] 2020-05-19 05:11
Hm... in my case, the  plugin doesn't work anymore.

Do I have to update may config.json?

`,
        {
            "platform": "yamaha-home",
            "show_input_name": "yes",
            "inputs_as_accessories": {
                "YamahaReceiver": {
                    "1": {
                        "name": "TV",
                        "set_scene": "1"
                    },
                    "2": {
                        "name": "Radio",
                        "set_scene": "2"
                    }
                }
            },
            "manual_addresses": {
                "Yamaha": "192.168.0.10"
            }
        }
`

**Comment by Hadea4711** [comment] 2020-05-19 05:35
`Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] Possible Yamaha device discovered Basti-AVR [ '192.168.0.10', 'fe80::66cc:22ff:fe0f:65a0' ]
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] Possible Yamaha device discovered Website on SMA3004908492 [ '192.168.0.61' ]
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] Possible Yamaha device discovered Mama-Kueche [ '192.168.0.121' ]
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] Possible Yamaha device discovered Medienspeicher [ '192.168.0.101' ]
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] Possible Yamaha device discovered shellydimmer-D0F09B [ '192.168.0.37' ]
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] Possible Yamaha device discovered shellydimmer-F35ED0 [ '192.168.0.43' ]
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] Possible Yamaha device discovered shelly1-C82B961159D7 [ '192.168.0.44' ]
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] Possible Yamaha device discovered shelly1-E098068D840F [ '192.168.0.51' ]
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] Possible Yamaha device discovered Website for SMA-Inverter: SMA3006472553 [ 'fe80::240:adff:feab:91d1', '192.168.0.62' ]
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] Possible Yamaha device discovered shellydimmer-F3A45B [ '192.168.0.33' ]
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] Possible Yamaha device discovered shelly1-E098068C9C44 [ '192.168.0.46' ]
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] Possible Yamaha device discovered shelly1-C82B9610E61E [ '192.168.0.31' ]
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] Possible Yamaha device discovered shellydimmer-D0EA15 [ '192.168.0.36' ]
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] Possible Yamaha device discovered shelly1-C82B961158BE [ '192.168.0.34' ]
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] Possible Yamaha device discovered shellyswitch25-1133C5 [ '192.168.0.40' ]
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] Possible Yamaha device discovered shelly1-10E295 [ '192.168.0.39' ]
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] Possible Yamaha device discovered shelly1-C82B96115B9F [ '192.168.0.48' ]
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] Possible Yamaha device discovered HP LaserJet P1606dn (Basti) [ '192.168.0.20', 'fe80::f6ce:46ff:fe45:1e68' ]
Mai 19 07:30:52 raspberrypi homebridge[7432]: OperationalError: socket hang up
Mai 19 07:30:52 raspberrypi homebridge[7432]:     at connResetException (internal/errors.js:583:14)
Mai 19 07:30:52 raspberrypi homebridge[7432]:     at Socket.socketOnEnd (_http_client.js:454:23)
Mai 19 07:30:52 raspberrypi homebridge[7432]:     at Socket.emit (events.js:317:22)
Mai 19 07:30:52 raspberrypi homebridge[7432]:     at endReadableNT (_stream_readable.js:1215:12)
Mai 19 07:30:52 raspberrypi homebridge[7432]:     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
Mai 19 07:30:52 raspberrypi homebridge[7432]:   cause: Error: socket hang up
Mai 19 07:30:52 raspberrypi homebridge[7432]:       at connResetException (internal/errors.js:583:14)
Mai 19 07:30:52 raspberrypi homebridge[7432]:       at Socket.socketOnEnd (_http_client.js:454:23)
Mai 19 07:30:52 raspberrypi homebridge[7432]:       at Socket.emit (events.js:317:22)
Mai 19 07:30:52 raspberrypi homebridge[7432]:       at endReadableNT (_stream_readable.js:1215:12)
Mai 19 07:30:52 raspberrypi homebridge[7432]:       at processTicksAndRejections (internal/process/task_queues.js:84:21) {
Mai 19 07:30:52 raspberrypi homebridge[7432]:     code: 'ECONNRESET'
Mai 19 07:30:52 raspberrypi homebridge[7432]:   },
Mai 19 07:30:52 raspberrypi homebridge[7432]:   isOperational: true,
Mai 19 07:30:52 raspberrypi homebridge[7432]:   code: 'ECONNRESET'
Mai 19 07:30:52 raspberrypi homebridge[7432]: }
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] DEBUG: Failed getSystemConfig from Website on SMA3004908492, probably just not a Yamaha AVR.
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] Found Yamaha RX-V685 - 0585F303, "Yamaha"
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] WARN: Got multiple systems with ID 0585F303! Omitting duplicate!
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] DEBUG: Failed getSystemConfig from shellydimmer-F35ED0, probably just not a Yamaha AVR.
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] DEBUG: Failed getSystemConfig from shelly1-C82B961159D7, probably just not a Yamaha AVR.
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] DEBUG: Failed getSystemConfig from shelly1-E098068D840F, probably just not a Yamaha AVR.
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] DEBUG: Failed getSystemConfig from shellydimmer-F3A45B, probably just not a Yamaha AVR.
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] DEBUG: Failed getSystemConfig from shelly1-E098068C9C44, probably just not a Yamaha AVR.
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] DEBUG: Failed getSystemConfig from shelly1-C82B9610E61E, probably just not a Yamaha AVR.
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] DEBUG: Failed getSystemConfig from shellydimmer-D0EA15, probably just not a Yamaha AVR.
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] DEBUG: Failed getSystemConfig from shelly1-C82B961158BE, probably just not a Yamaha AVR.
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] DEBUG: Failed getSystemConfig from shellyswitch25-1133C5, probably just not a Yamaha AVR.
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] DEBUG: Failed getSystemConfig from shelly1-10E295, probably just not a Yamaha AVR.
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] DEBUG: Failed getSystemConfig from shelly1-C82B96115B9F, probably just not a Yamaha AVR.
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] DEBUG: Failed getSystemConfig from shellydimmer-D0F09B, probably just not a Yamaha AVR.
Mai 19 07:30:52 raspberrypi homebridge[7432]: [19.5.2020, 07:30:52] [yamaha-home] Adding zone controller for Wohnen
Mai 19 07:30:53 raspberrypi homebridge[7432]: [19.5.2020, 07:30:53] [yamaha-home] Adding zone controller for Garten
`

**Comment by Hadea4711** [comment] 2020-05-19 05:37
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/58209844/82288795-94007b80-99a3-11ea-86e8-bcb0a4239238.png">

**Comment by Hadea4711** [comment] 2020-05-19 05:38
My scenes doesn't appear anymore :-(.

**Comment by NorthernMan54** [comment] 2020-05-20 00:03
With the latest version, you need to change "YamahaReceiver" to be your Receiver name "Yamaha"

**Comment by Hadea4711** [comment] 2020-05-20 07:11
Thanks. It works!!!

**Comment by proactivematter** [comment] 2020-08-08 20:17
Hey @NorthernMan54. My receiver network name is RX-V583 (Wireless), but accessories don't show up. What am I doing wrong, please? Thank you.

`        {
            "platform": "yamaha-home",
            "play_volume": -48,
            "min_volume": -80,
            "max_volume": 10,
            "setMainInputTo": "Airplay",
            "show_input_name": "yes",
            "party_switch": "no",
            "inputs_as_accessories": {
                "RX-V583 (Wireless)": {
                    "1": {
                        "name": "Raspberry",
                        "setInputTo": "HDMI1",
                        "set_default_volume": -49
                    },
                    "2": {
                        "name": "AppleTV",
                        "setInputTo": "HDMI2"
                    },
                    "3": {
                        "name": "Scene 3",
                        "set_scene": "3",
                        "setInputTo": "HDMI3"
                    }
                }
            },
            "manual_addresses": {
                "Yamaha": "192.168.2.10"
            }
        }`

**Comment by NorthernMan54** [comment] 2020-08-09 04:25
Can you share a log from the plugin, it may show why it isn’t working

**Comment by proactivematter** [comment] 2020-08-09 12:08
Here it is. I have extracted only yamaha-home entries; Homebridge reboots are not shown. Please let me know if you need anything else.

[8/8/2020, 4:51:58 PM] [yamaha-home] Found Yamaha RX-V583 - 0DABE453, "Yamaha"
[8/8/2020, 4:51:58 PM] [yamaha-home] Possible Yamaha device discovered RX-V583 (Wireless) [ '192.168.2.10' ]
[8/8/2020, 4:51:58 PM] [yamaha-home] WARN: Got multiple systems with ID 0DABE453! Omitting duplicate!
[8/8/2020, 4:51:58 PM] [yamaha-home] Adding zone controller for Main
[8/8/2020, 4:52:13 PM] [yamaha-home] Waited 10 seconds, stopping discovery.
[8/8/2020, 4:52:13 PM] [yamaha-home] Discovery finished, found 1 Yamaha AVR devices.
[8/8/2020, 4:52:13 PM] Initializing platform accessory 'Main'...
[8/8/2020, 5:33:50 PM] [yamaha-home] Initializing yamaha-home platform...
[8/8/2020, 5:33:50 PM] [yamaha-home] Getting Yamaha AVR devices.
[8/8/2020, 5:33:50 PM] [yamaha-home] Possible Yamaha device discovered Yamaha undefined
[8/8/2020, 5:27:32 PM] [yamaha-home] Found Yamaha RX-V583 - 0DABE453, "Yamaha"
[8/8/2020, 5:27:32 PM] [yamaha-home] Possible Yamaha device discovered RX-V583 (Wireless) [ '192.168.2.10' ]
[8/8/2020, 5:27:32 PM] [yamaha-home] WARN: Got multiple systems with ID 0DABE453! Omitting duplicate!
[8/8/2020, 5:27:33 PM] [yamaha-home] Adding zone controller for Main
[8/8/2020, 5:27:48 PM] [yamaha-home] Waited 10 seconds, stopping discovery.
[8/8/2020, 5:27:48 PM] [yamaha-home] Discovery finished, found 1 Yamaha AVR devices.
[8/8/2020, 5:27:48 PM] Initializing platform accessory 'Main'...
[8/8/2020, 5:33:50 PM] [yamaha-home] Initializing yamaha-home platform...
[8/8/2020, 5:33:50 PM] [yamaha-home] Getting Yamaha AVR devices.
[8/8/2020, 5:33:50 PM] [yamaha-home] Possible Yamaha device discovered Yamaha undefined
[8/8/2020, 5:33:51 PM] [yamaha-home] Found Yamaha RX-V583 - 0DABE453, "Yamaha"
[8/8/2020, 5:33:51 PM] [yamaha-home] Possible Yamaha device discovered RX-V583(Wireless) [ '192.168.2.10' ]
[8/8/2020, 5:33:51 PM] [yamaha-home] WARN: Got multiple systems with ID 0DABE453! Omitting duplicate!
[8/8/2020, 5:33:51 PM] [yamaha-home] Adding zone controller for Main
[8/8/2020, 5:34:06 PM] [yamaha-home] Waited 10 seconds, stopping discovery.
[8/8/2020, 5:34:06 PM] [yamaha-home] Discovery finished, found 1 Yamaha AVR devices.
[8/8/2020, 5:34:06 PM] Initializing platform accessory 'Main'...

**Comment by proactivematter** [comment] 2020-08-10 17:44
Seems it is actually having trouble identifying the AVR, in some way, or there is some inconsistency.

[8/10/2020, 12:25:05 PM] [yamaha-home] Initializing yamaha-home platform...
[8/10/2020, 12:25:05 PM] [yamaha-home] Getting Yamaha AVR devices.
[8/10/2020, 12:25:05 PM] [yamaha-home] Possible Yamaha device discovered Yamaha undefined
[8/10/2020, 12:25:28 PM] [yamaha-home] Waited 10 seconds, stopping discovery.
[8/10/2020, 12:25:28 PM] [yamaha-home] Discovery finished, found 0 Yamaha AVR devices.
[8/10/2020, 12:26:32 PM] [yamaha-home] DEBUG: Failed getSystemConfig from Yamaha, probably just not a Yamaha AVR.

**Comment by NorthernMan54** [comment] 2020-08-11 14:22
@proactivematter If you enable debug the plugin will log a lot more details about your stereo to determine why it isn't working.  Also you shouldn't need the manual address config section as the plugin is detecting your receiver.  To enable debug, you need to start Homebridge from the command line like this.  If you using autostart scripts etc, you will need to disable the autostart first

```
DEBUG=yamaha-home homebridge
```

**Comment by proactivematter** [comment] 2020-08-11 21:17
DEBUG=yamaha-home homebridge

[8/11/2020, 5:12:05 PM] Loaded config.json with 0 accessories and 4 platforms.
[8/11/2020, 5:12:05 PM] ---
[8/11/2020, 5:12:06 PM] Loaded plugin: homebridge-bravia-tvos@3.0.7
[8/11/2020, 5:12:06 PM] Registering platform 'homebridge-bravia-tvos.BraviaOSPlatform'
[8/11/2020, 5:12:06 PM] ---
[8/11/2020, 5:12:06 PM] Loaded plugin: homebridge-config-ui-x@4.24.0
[8/11/2020, 5:12:06 PM] Registering platform 'homebridge-config-ui-x.config'
[8/11/2020, 5:12:06 PM] ---
[8/11/2020, 5:12:06 PM] Loaded plugin: homebridge-lg-thinq-ac@1.7.0
[8/11/2020, 5:12:06 PM] Registering platform 'homebridge-lg-thinq-ac.LgThinqAirConditioner'
[8/11/2020, 5:12:06 PM] ---
[8/11/2020, 5:12:06 PM] Loaded plugin: homebridge-yamaha-home@0.1.10
[8/11/2020, 5:12:06 PM] Registering platform 'homebridge-yamaha-home.yamaha-home'
[8/11/2020, 5:12:06 PM] ---
[8/11/2020, 5:12:06 PM] Loading 4 platforms...
[8/11/2020, 5:12:06 PM] [Config] Initializing config platform...
[8/11/2020, 5:12:06 PM] [Config] Spawning homebridge-config-ui-x with PID 64181
[8/11/2020, 5:12:06 PM] [LgThinqAirConditioner] Initializing LgThinqAirConditioner platform...
[8/11/2020, 5:12:06 PM] [BraviaOSPlatform] Initializing BraviaOSPlatform platform...
[8/11/2020, 5:12:06 PM] [BraviaOSPlatform] **************************************************************
[8/11/2020, 5:12:06 PM] [BraviaOSPlatform] BraviaOSPlatform v3.0.7 by SeydX
[8/11/2020, 5:12:06 PM] [BraviaOSPlatform] GitHub: https://github.com/SeydX/homebridge-bravia-tvos
[8/11/2020, 5:12:06 PM] [BraviaOSPlatform] Email: seyd55@outlook.de
[8/11/2020, 5:12:06 PM] [BraviaOSPlatform] **************************************************************
[8/11/2020, 5:12:06 PM] [BraviaOSPlatform] start success...
[8/11/2020, 5:12:06 PM] [yamaha-home] Initializing yamaha-home platform...
[8/11/2020, 5:12:06 PM] [yamaha-home] Getting Yamaha AVR devices.
  yamaha-home THIS-0 {
  log: [Function: bound info] {
    info: [Function: info],
    warn: [Function: warn],
    error: [Function: error],
    debug: [Function: debug],
    log: [Function: log],
    prefix: 'yamaha-home'
  },
  config: {
    platform: 'yamaha-home',
    play_volume: -48,
    min_volume: -80,
    max_volume: 10,
    setMainInputTo: 'HDMI_4',
    show_input_name: 'yes',
    party_switch: 'no',
    inputs_as_accessories: { 'RX-V583 (Wireless)': [Object] },
    manual_addresses: { Yamaha: '192.168.2.10' }
  },
  zone: 'Main',
  playVolume: -48,
  minVolume: -80,
  maxVolume: 10,
  gapVolume: 90,
  showInputName: 'yes',
  setMainInputTo: 'HDMI_4',
  expectedDevices: 100,
  discoveryTimeout: 10,
  radioPresets: false,
  presetNum: false,
  manualAddresses: { Yamaha: '192.168.2.10' },
  spotifyControls: false,
  nozones: false,
  partySwitch: 'no',
  inputAccessories: {
    'RX-V583 (Wireless)': { '1': [Object], '2': [Object], '3': [Object], '4': [Object] }
  },
  zoneControllersOnlyFor: null
} +0ms
[8/11/2020, 5:12:06 PM] [yamaha-home] Possible Yamaha device discovered Yamaha undefined
  yamaha-home Is this a Yamaha ? Yamaha 192.168.2.10 +2ms
  yamaha-home SysConfig -> Yamaha -> {
  "YAMAHA_AV": {
    "$": {
      "rsp": "GET",
      "RC": "0"
    },
    "System": [
      {
        "Config": [
          {
            "Model_Name": [
              "RX-V583"
            ],
            "System_ID": [
              "0DABE453"
            ],
            "Version": [
              "2.70/1.70"
            ],
            "Feature_Existence": [
              {
                "Main_Zone": [
                  "1"
                ],
                "Zone_2": [
                  "0"
                ],
                "Zone_3": [
                  "0"
                ],
                "Zone_4": [
                  "0"
                ],
                "Tuner": [
                  "1"
                ],
                "DAB": [
                  "0"
                ],
                "Napster": [
                  "0"
                ],
                "SiriusXM": [
                  "0"
                ],
                "Pandora": [
                  "1"
                ],
                "Spotify": [
                  "1"
                ],
                "JUKE": [
                  "0"
                ],
                "Qobuz": [
                  "0"
                ],
                "radiko_jp": [
                  "0"
                ],
                "TIDAL": [
                  "1"
                ],
                "Deezer": [
                  "1"
                ],
                "AirPlay": [
                  "1"
                ],
                "MusicCast_Link": [
                  "0"
                ],
                "SERVER": [
                  "1"
                ],
                "NET_RADIO": [
                  "1"
                ],
                "Bluetooth": [
                  "1"
                ],
                "USB": [
                  "1"
                ]
              }
            ],
            "Name": [
              {
                "Input": [
                  {
                    "TUNER": [
                      "TUNER"
                    ],
                    "HDMI_1": [
                      "Empty"
                    ],
                    "HDMI_2": [
                      "Empty"
                    ],
                    "HDMI_3": [
                      "PC"
                    ],
                    "HDMI_4": [
                      "Mac"
                    ],
                    "AV_1": [
                      "N-1"
                    ],
                    "AV_2": [
                      "N-2"
                    ],
                    "AV_3": [
                      "N-3"
                    ],
                    "AUX": [
                      "AUX"
                    ],
                    "AUDIO_1": [
                      "N-4"
                    ],
                    "AUDIO_2": [
                      "N-5"
                    ],
                    "AUDIO_3": [
                      "N-6"
                    ],
                    "MusicCast_Link": [
                      "MusicCast Link"
                    ],
                    "SERVER": [
                      "SERVER"
                    ],
                    "NET_RADIO": [
                      "NET RADIO"
                    ],
                    "Bluetooth": [
                      "Bluetooth"
                    ],
                    "USB": [
                      "USB"
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  }
} +59ms
[8/11/2020, 5:12:06 PM] [yamaha-home] Found Yamaha RX-V583 - 0DABE453, "Yamaha"
[8/11/2020, 5:12:06 PM] [yamaha-home] Possible Yamaha device discovered RX-V583 (Wireless) [ '192.168.2.10' ]
  yamaha-home Is this a Yamaha ? RX-V583 (Wireless) 192.168.2.10 +63ms
[8/11/2020, 5:12:06 PM] [yamaha-home] Adding zone controller for Main
  yamaha-home SysConfig -> RX-V583 (Wireless) -> {
  "YAMAHA_AV": {
    "$": {
      "rsp": "GET",
      "RC": "0"
    },
    "System": [
      {
        "Config": [
          {
            "Model_Name": [
              "RX-V583"
            ],
            "System_ID": [
              "0DABE453"
            ],
            "Version": [
              "2.70/1.70"
            ],
            "Feature_Existence": [
              {
                "Main_Zone": [
                  "1"
                ],
                "Zone_2": [
                  "0"
                ],
                "Zone_3": [
                  "0"
                ],
                "Zone_4": [
                  "0"
                ],
                "Tuner": [
                  "1"
                ],
                "DAB": [
                  "0"
                ],
                "Napster": [
                  "0"
                ],
                "SiriusXM": [
                  "0"
                ],
                "Pandora": [
                  "1"
                ],
                "Spotify": [
                  "1"
                ],
                "JUKE": [
                  "0"
                ],
                "Qobuz": [
                  "0"
                ],
                "radiko_jp": [
                  "0"
                ],
                "TIDAL": [
                  "1"
                ],
                "Deezer": [
                  "1"
                ],
                "AirPlay": [
                  "1"
                ],
                "MusicCast_Link": [
                  "0"
                ],
                "SERVER": [
                  "1"
                ],
                "NET_RADIO": [
                  "1"
                ],
                "Bluetooth": [
                  "1"
                ],
                "USB": [
                  "1"
                ]
              }
            ],
            "Name": [
              {
                "Input": [
                  {
                    "TUNER": [
                      "TUNER"
                    ],
                    "HDMI_1": [
                      "Empty"
                    ],
                    "HDMI_2": [
                      "Empty"
                    ],
                    "HDMI_3": [
                      "PC"
                    ],
                    "HDMI_4": [
                      "Mac"
                    ],
                    "AV_1": [
                      "N-1"
                    ],
                    "AV_2": [
                      "N-2"
                    ],
                    "AV_3": [
                      "N-3"
                    ],
                    "AUX": [
                      "AUX"
                    ],
                    "AUDIO_1": [
                      "N-4"
                    ],
                    "AUDIO_2": [
                      "N-5"
                    ],
                    "AUDIO_3": [
                      "N-6"
                    ],
                    "MusicCast_Link": [
                      "MusicCast Link"
                    ],
                    "SERVER": [
                      "SERVER"
                    ],
                    "NET_RADIO": [
                      "NET RADIO"
                    ],
                    "Bluetooth": [
                      "Bluetooth"
                    ],
                    "USB": [
                      "USB"
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  }
} +35ms
[8/11/2020, 5:12:06 PM] [yamaha-home] WARN: Got multiple systems with ID 0DABE453! Omitting duplicate!
[8/11/2020, 5:12:08 PM] [Config] Homebridge Config UI X v4.24.0 is listening on :: port 8588
[8/11/2020, 5:12:08 PM] [Config] Error: listen EADDRINUSE: address already in use :::8588
[8/11/2020, 5:12:08 PM] [Config] Another process or service on this host is using port 8588.
[8/11/2020, 5:12:08 PM] [Config] Please stop the other service or change the port you have assigned to homebridge-config-ui-x.
[8/11/2020, 5:12:08 PM] [Config] Ending process now.
[8/11/2020, 5:12:08 PM] Got SIGTERM, shutting down Homebridge...

**Comment by NorthernMan54** [comment] 2020-08-13 13:59
Those logs appear normal, and you should have a "Fan" called Main in your setup.

```
[8/11/2020, 5:12:06 PM] [yamaha-home] Adding zone controller for Main
```

**Comment by proactivematter** [comment] 2020-08-13 14:32
Yes, I do see the “Main” fan in AppleHome and I can turn the AV ON/OFF and control it’s volume.

The issue is that inputs I specified in Config.json are not showing up as acessories. The only 2 acessories are power and volume.

**Comment by NorthernMan54** [comment] 2020-08-13 16:04
Shoot missed that comment

```
[8/11/2020, 5:12:06 PM] [yamaha-home] Found Yamaha RX-V583 - 0DABE453, "Yamaha"
```

In your config it is looking for **Yamaha** for inputs_as_accessories and not **RX-V583 (Wireless)**

**Comment by proactivematter** [comment] 2020-08-13 16:19
Ahh, thank you!!

The issue was that I had based my config.json off the advanced configuration example you gave, and that included **manual_addresses**. Once I changed it from **Yamaha** to **RX-V583 (Wireless)**, the zones appeared. I have of course just removed **manual_addresses** entirely now and everything works perfect :)

**Closed** 2020-08-18 12:44 UTC

**Comment by NorthernMan54** [comment] 2020-08-18 12:46
The name Main comes from the Zone name provided by the receiver.  And with my receiver I can change it there.

If that is not an option, you can always change the name in home App.
